### ISSUE TITLE
romanNumeral.js file missing

### ISSUE THREAD

**Issue by mrname5** [Yiler7274/Konduktiva-github-test#7]
In your readme there is this line:
#These are the instructions of how to use a particular file (romanNumeral.js) to play different chord progression with a virtual MIDI synthesizer.

I cannot find romanNumeral.js

**Comment by mrname5** [comment]
I think you might mean example session because in that file it says romanNumeral.js. You might want to change that

**Comment by Yiler7274** [comment]
I updated the readme file
